tclmode

# Generated by Genus(TM) Synthesis Solution 21.16-s062_1, revision 1.566
# Generated on: Thu Oct 12 10:28:11 -03 2023 (Thu Oct 12 13:28:11 UTC 2023)

set_screen_display -noprogress
set_dofile_abort exit

### Alias mapping flow is enabled. ###
# Root attribute 'alias_flow'                 was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         false

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set logfile fv/FFT/rtl_to_fv_map.log ;# user can modify this name for succeeding runs

set_log_file $logfile -replace

usage -auto -elapse

set_mapping_method -sensitive

set_verification_information rtl_fv_map_db

read_implementation_information fv/FFT -revised fv_map

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "21.16-s062_1"
set env(CDN_SYNTH_ROOT) "/opt/cadence/GENUS211/tools.lnx86"
set CDN_SYNTH_ROOT      "/opt/cadence/GENUS211/tools.lnx86"
set env(CW_DIR) "/opt/cadence/GENUS211/tools.lnx86/lib/chipware"
set CW_DIR      "/opt/cadence/GENUS211/tools.lnx86/lib/chipware"
set lec_version_required "21.20249"
if { ($lec_version < $lec_version_required) &&
    [file exists /opt/cadence/GENUS211/tools.lnx86/lib/chipware/old_encrypt_sim]} {
    set env(CW_DIR_SIM) "/opt/cadence/GENUS211/tools.lnx86/lib/chipware/old_encrypt_sim"
    set CW_DIR_SIM      "/opt/cadence/GENUS211/tools.lnx86/lib/chipware/old_encrypt_sim"
} else {
    set env(CW_DIR_SIM) "/opt/cadence/GENUS211/tools.lnx86/lib/chipware/sim"
    set CW_DIR_SIM      "/opt/cadence/GENUS211/tools.lnx86/lib/chipware/sim"
}
set_multiplier_implementation boothrca -both

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

# ILM modules: 

add_search_path /home/xmen/Programas/cadence/GENUS211/fftv1/gsclib045_all_v4.7/gsclib045_tech/techfile  /home/xmen/Programas/cadence/GENUS211/fftv1/gsclib045_all_v4.7/gsclib045_tech/oa22/gsclib045_tech /home/xmen/Programas/cadence/GENUS211/fftv1/gsclib045_all_v4.7/gsclib045/techfile -library -both
read_library -liberty -both \
    /home/xmen/Programas/cadence/GENUS211/fftv1/gsclib045_all_v4.7/gsclib045/timing/fast_vdd1v0_basicCells.lib

set_undriven_signal 0 -golden
set lec_version_required "16.20100"
if {$lec_version >= $lec_version_required} {
    set_naming_style genus -golden
} else {
    set_naming_style rc -golden
}
set_naming_rule "_" "" -array_delimiter -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden
set lec_version_required "17.10200"
if {$lec_version >= $lec_version_required} {
    set_naming_rule -ungroup_separator {_} -golden
}

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue.
# This option is only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -SKIP_UNNAMED_BLK_NAMING ON
set_hdl_options -unsigned_conversion_overflow on
set_hdl_option -v_to_vd on

set lec_version_required "20.20226"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -VERILOG_INCLUDE_DIR "sep:src"
} else {
    set_hdl_options -VERILOG_INCLUDE_DIR "sep:src:cwd"
}
delete_search_path -all -design -golden
add_search_path ../../rtl/designs -design -golden
read_design -enumconstraint -define SYNTHESIS -keep_unreach -merge bbox -golden -lastmod -noelab  -sv09 ../../rtl/designs/FFT.sv ../../rtl/designs/computeMatrix.sv
elaborate_design -golden -root {FFT} -rootonly -rootonly  

read_design -verilog95   -revised -lastmod -noelab fv/FFT/fv_map.v.gz
elaborate_design -revised -root {FFT}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

set_flatten_model -balanced_modeling

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

set_system_mode lec
analyze_datapath -module -verbose
eval analyze_datapath $DATAPATH_SOLVER_OPTION -verbose
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_compared_points noneq.compared_points.FFT.rtl.fv_map.tcl -class noneq -tclmode -replace
set lec_version_required "21.10100"
if {$lec_version >= $lec_version_required} {
    analyze_nonequivalent -source_diagnosis
    report_nonequivalent_analysis > noneq.source_diag.FFT.rtl.fv_map.rpt
}
report_test_vector -noneq > noneq.test_vector.FFT.rtl.fv_map.rpt
write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
    analyze_results -logfiles $logfile
}

vpxmode

exit -f
